### PR TITLE
Added Set-Variable machine

### PR DESCRIPTION
**Pull request by NileFrater**
Really simple machine for Treeline that takes any input and turns it into a CTRL+I-accessible variable.

### CODE REVIEW

**Comment by sgress454** [comment]
Interesting, what's the use case you're thinking of here?  Project config vars can fill this role, but they're obviously project-wide; is this intended to fulfill the same purpose for a single circuit?

**Comment by NileFrater** [comment]
That's one use, yeah. Another use case is placing a variable at the circuit
exit that was created more than one level above.

**Comment by sgress454** [comment]
> Another use case is placing a variable at the circuit
> exit that was created more than one level above.

You should already be able do that.  If it's not working somewhere, send me a link!

**Comment by NileFrater** [comment]
I had that issue when I first opened this pull request but I completely
scrapped the circuit since. I'll see if I can re-create the issue I had and
drop you a link.

**Comment by mikermcneil** [comment]
@nilefrater thanks- let us know if you still need this (I usually use the "if defined" machine)

**Pull request closed without merging**
